// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PMRU.Persistence.Context;

#nullable disable

namespace PMRU.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240202132245_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("faad6812-0f8e-4342-8738-6dcd5e8ecc09"),
                            RoleId = new Guid("01b33042-952a-4636-8d15-682447de311a")
                        },
                        new
                        {
                            UserId = new Guid("a76eb5c4-eebf-47ec-a274-ca7971bfa4e8"),
                            RoleId = new Guid("e3a11d19-3f92-463a-a80d-38228fa18746")
                        },
                        new
                        {
                            UserId = new Guid("a3b9e2f7-5c1d-4a88-9f3b-7e6c4d2a1b11"),
                            RoleId = new Guid("e3a11d19-3f92-463a-a80d-38228fa18746")
                        },
                        new
                        {
                            UserId = new Guid("e2f8d174-4b7a-4c91-b9f2-8dc3a1c45b68"),
                            RoleId = new Guid("e3a11d19-3f92-463a-a80d-38228fa18746")
                        },
                        new
                        {
                            UserId = new Guid("0e7b95a1-9b14-4c87-af3d-1d2f6b8aefc3"),
                            RoleId = new Guid("e3a11d19-3f92-463a-a80d-38228fa18746")
                        },
                        new
                        {
                            UserId = new Guid("2b9d163d-cdd1-4b2c-b62e-ec59a6b300fb"),
                            RoleId = new Guid("e3a11d19-3f92-463a-a80d-38228fa18746")
                        },
                        new
                        {
                            UserId = new Guid("b4f91e33-68d1-4aee-b254-d8a53631b23a"),
                            RoleId = new Guid("e3a11d19-3f92-463a-a80d-38228fa18746")
                        },
                        new
                        {
                            UserId = new Guid("79a21042-ac37-43dc-b246-e1a2c9645afb"),
                            RoleId = new Guid("b56d0892-1daa-4b5d-a6e0-381a250daea1")
                        },
                        new
                        {
                            UserId = new Guid("faad6812-0f8e-4342-aabb-6dcd5e8ecc09"),
                            RoleId = new Guid("b56d0892-1daa-4b5d-a6e0-381a250daea1")
                        },
                        new
                        {
                            UserId = new Guid("a2b4f813-72c9-4a6e-9d7b-1f8c3d2e5a0f"),
                            RoleId = new Guid("b56d0892-1daa-4b5d-a6e0-381a250daea1")
                        },
                        new
                        {
                            UserId = new Guid("3a7f9b68-21d5-4f8c-b2a7-9c0e1f5d2a91"),
                            RoleId = new Guid("b56d0892-1daa-4b5d-a6e0-381a250daea1")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PMRU.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("AppointmentEndHour")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("AppointmentStartHour")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorID");

                    b.HasIndex("EmployeeID")
                        .IsUnique();

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateOnly(2024, 1, 1),
                            AppointmentEndHour = new TimeOnly(8, 20, 0),
                            AppointmentStartHour = new TimeOnly(8, 0, 0),
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(133),
                            Description = "Regular Checkup",
                            DoctorID = 1,
                            EmployeeID = 1,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateOnly(2024, 1, 1),
                            AppointmentEndHour = new TimeOnly(8, 20, 0),
                            AppointmentStartHour = new TimeOnly(8, 0, 0),
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(163),
                            Description = "Regular Checkup",
                            DoctorID = 2,
                            EmployeeID = 2,
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("PMRU.Domain.Entities.Availability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DoctorID");

                    b.ToTable("Availabilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(2743),
                            Date = new DateOnly(2024, 1, 2),
                            DoctorID = 1,
                            EndTime = new TimeOnly(8, 20, 0),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(2751),
                            Date = new DateOnly(2024, 1, 2),
                            DoctorID = 1,
                            EndTime = new TimeOnly(8, 40, 0),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new TimeOnly(8, 20, 0)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(2753),
                            Date = new DateOnly(2024, 1, 2),
                            DoctorID = 1,
                            EndTime = new TimeOnly(9, 0, 0),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new TimeOnly(8, 40, 0)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(2754),
                            Date = new DateOnly(2024, 1, 2),
                            DoctorID = 2,
                            EndTime = new TimeOnly(8, 20, 0),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(2756),
                            Date = new DateOnly(2024, 1, 2),
                            DoctorID = 2,
                            EndTime = new TimeOnly(8, 40, 0),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new TimeOnly(8, 20, 0)
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(2757),
                            Date = new DateOnly(2024, 1, 2),
                            DoctorID = 2,
                            EndTime = new TimeOnly(9, 0, 0),
                            IsActive = true,
                            IsDeleted = false,
                            StartTime = new TimeOnly(8, 40, 0)
                        });
                });

            modelBuilder.Entity("PMRU.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentDescription = "Güvenlik",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            DepartmentDescription = "Üretim",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            DepartmentDescription = "Finans",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            DepartmentDescription = "İnsan Kaynakları",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            DepartmentDescription = "Satış Pazarlama",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            DepartmentDescription = "IT",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            DepartmentDescription = "Sağlık",
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("PMRU.Domain.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LocationID");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "aylin.gunes@email.com",
                            IdentityNumber = "12345678901",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 35,
                            Name = "Aylin",
                            Phone = "5556123456",
                            RegistrationNumber = "110",
                            Surname = "Güneş"
                        },
                        new
                        {
                            Id = 2,
                            Email = "eren.akcay@email.com",
                            IdentityNumber = "12345678923",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 41,
                            Name = "Eren",
                            Phone = "5556234567",
                            RegistrationNumber = "111",
                            Surname = "Akçay"
                        },
                        new
                        {
                            Id = 3,
                            Email = "gulay.kaya@email.com",
                            IdentityNumber = "12343458923",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 72,
                            Name = "Gülay",
                            Phone = "5556345678",
                            RegistrationNumber = "112",
                            Surname = "Kaya"
                        },
                        new
                        {
                            Id = 4,
                            Email = "gulsum.aydin@email.com",
                            IdentityNumber = "12343458205",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 34,
                            Name = "Gülsüm",
                            Phone = "5556678901",
                            RegistrationNumber = "116",
                            Surname = "Aydın"
                        },
                        new
                        {
                            Id = 5,
                            Email = "meryem.kuzey@email.com",
                            IdentityNumber = "3972226751",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 35,
                            Name = "Meryem",
                            Phone = "5556345358",
                            RegistrationNumber = "121",
                            Surname = "Kuzey"
                        },
                        new
                        {
                            Id = 6,
                            Email = "ali.atabey@email.com",
                            IdentityNumber = "1971927981",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 34,
                            Name = "Ali",
                            Phone = "5551862565",
                            RegistrationNumber = "122",
                            Surname = "Atabey"
                        });
                });

            modelBuilder.Entity("PMRU.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("PositionID")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("LocationID");

                    b.HasIndex("PositionID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 0,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(8869),
                            DepartmentID = 4,
                            Email = "ahmet.yilmaz@email.com",
                            IdentityNumber = "5555123456",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 34,
                            Name = "Ahmet",
                            Phone = "(555) 512-3456",
                            PositionID = 4,
                            RegistrationNumber = "100",
                            Surname = "Yılmaz"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 0,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(8912),
                            DepartmentID = 4,
                            Email = "ayse.kaya@email.com",
                            IdentityNumber = "5555234567",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 41,
                            Name = "Ayşe",
                            Phone = "(555) 523-4567",
                            PositionID = 3,
                            RegistrationNumber = "101",
                            Surname = "Kaya"
                        },
                        new
                        {
                            Id = 3,
                            AppointmentId = 0,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(8916),
                            DepartmentID = 3,
                            Email = "mehmet.celik@email.com",
                            IdentityNumber = "5278149630",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 35,
                            Name = "Mehmet",
                            Phone = "(555) 534-5678",
                            PositionID = 5,
                            RegistrationNumber = "102",
                            Surname = "Çelik"
                        },
                        new
                        {
                            Id = 4,
                            AppointmentId = 0,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(8919),
                            DepartmentID = 4,
                            Email = "fatma.arslan@email.com",
                            IdentityNumber = "5555456789",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 71,
                            Name = "Fatma",
                            Phone = "(555) 545-6789",
                            PositionID = 6,
                            RegistrationNumber = "103",
                            Surname = "Arslan"
                        },
                        new
                        {
                            Id = 5,
                            AppointmentId = 0,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(8922),
                            DepartmentID = 2,
                            Email = "ali.demir@email.com",
                            IdentityNumber = "5555567890",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 72,
                            Name = "Ali",
                            Phone = "(555) 556-7890",
                            PositionID = 2,
                            RegistrationNumber = "104",
                            Surname = "Demir"
                        },
                        new
                        {
                            Id = 6,
                            AppointmentId = 0,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(8924),
                            DepartmentID = 5,
                            Email = "zeynep.yildiz@email.com",
                            IdentityNumber = "5555678901",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 35,
                            Name = "Zeynep",
                            Phone = "(555) 567-8901",
                            PositionID = 14,
                            RegistrationNumber = "105",
                            Surname = "Yıldız"
                        },
                        new
                        {
                            Id = 7,
                            AppointmentId = 0,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(8927),
                            DepartmentID = 2,
                            Email = "can.aksoy@email.com",
                            IdentityNumber = "5555789012",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 41,
                            Name = "Can",
                            Phone = "(555) 578-9012",
                            PositionID = 4,
                            RegistrationNumber = "106",
                            Surname = "Aksoy"
                        },
                        new
                        {
                            Id = 8,
                            AppointmentId = 0,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(8931),
                            DepartmentID = 6,
                            Email = "elif.ersoy@email.com",
                            IdentityNumber = "5555890123",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 34,
                            Name = "Elif",
                            Phone = "(555) 589-0123",
                            PositionID = 8,
                            RegistrationNumber = "107",
                            Surname = "Ersoy"
                        },
                        new
                        {
                            Id = 9,
                            AppointmentId = 0,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(8933),
                            DepartmentID = 4,
                            Email = "burak.taskin@email.com",
                            IdentityNumber = "5555901234",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 72,
                            Name = "Burak",
                            Phone = "(555) 590-1234",
                            PositionID = 7,
                            RegistrationNumber = "108",
                            Surname = "Taşkın"
                        },
                        new
                        {
                            Id = 10,
                            AppointmentId = 0,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(8943),
                            DepartmentID = 1,
                            Email = "deniz.akin@email.com",
                            IdentityNumber = "5556012345",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 71,
                            Name = "Deniz",
                            Phone = "(555) 601-2345",
                            PositionID = 2,
                            RegistrationNumber = "109",
                            Surname = "Akın"
                        },
                        new
                        {
                            Id = 11,
                            AppointmentId = 0,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(8949),
                            DepartmentID = 7,
                            Email = "aylin.gunes@email.com",
                            IdentityNumber = "5642597451",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 35,
                            Name = "Aylin",
                            Phone = "(555) 612-3456",
                            PositionID = 12,
                            RegistrationNumber = "110",
                            Surname = "Güneş"
                        },
                        new
                        {
                            Id = 12,
                            AppointmentId = 0,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(8959),
                            DepartmentID = 7,
                            Email = "eren.akcay@email.com",
                            IdentityNumber = "5642517451",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 41,
                            Name = "Eren",
                            Phone = "(555) 623-4567",
                            PositionID = 12,
                            RegistrationNumber = "111",
                            Surname = "Akçay"
                        },
                        new
                        {
                            Id = 13,
                            AppointmentId = 0,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(8962),
                            DepartmentID = 7,
                            Email = "gulay.kaya@email.com",
                            IdentityNumber = "3462517451",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 72,
                            Name = "Gülay",
                            Phone = "(555) 634-5678",
                            PositionID = 12,
                            RegistrationNumber = "112",
                            Surname = "Kaya"
                        },
                        new
                        {
                            Id = 14,
                            AppointmentId = 0,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(8965),
                            DepartmentID = 7,
                            Email = "cem.yildirim@email.com",
                            IdentityNumber = "3434517451",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 35,
                            Name = "Cem",
                            Phone = "(555) 645-6789",
                            PositionID = 13,
                            RegistrationNumber = "113",
                            Surname = "Yıldırım"
                        },
                        new
                        {
                            Id = 15,
                            AppointmentId = 0,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(8968),
                            DepartmentID = 7,
                            Email = "dilara.cetin@email.com",
                            IdentityNumber = "3434546751",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 72,
                            Name = "Dilara",
                            Phone = "(555) 656-7890",
                            PositionID = 13,
                            RegistrationNumber = "114",
                            Surname = "Çetin"
                        },
                        new
                        {
                            Id = 16,
                            AppointmentId = 0,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(8971),
                            DepartmentID = 7,
                            Email = "mert.saglam@email.com",
                            IdentityNumber = "3432209751",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 41,
                            Name = "Mert",
                            Phone = "(535) 896-4526",
                            PositionID = 13,
                            RegistrationNumber = "115",
                            Surname = "Sağlam"
                        },
                        new
                        {
                            Id = 17,
                            AppointmentId = 0,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(8973),
                            DepartmentID = 7,
                            Email = "gulsum.aydin@email.com",
                            IdentityNumber = "3432906751",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 34,
                            Name = "Gülsüm",
                            Phone = "(555) 667-8901",
                            PositionID = 12,
                            RegistrationNumber = "116",
                            Surname = "Aydın"
                        },
                        new
                        {
                            Id = 18,
                            AppointmentId = 0,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(8976),
                            DepartmentID = 7,
                            Email = "emre.yaman@email.com",
                            IdentityNumber = "3850906751",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 34,
                            Name = "Emre",
                            Phone = "(555) 678-9012",
                            PositionID = 13,
                            RegistrationNumber = "117",
                            Surname = "Yaman"
                        },
                        new
                        {
                            Id = 19,
                            AppointmentId = 0,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(8978),
                            DepartmentID = 5,
                            Email = "selin.erdogan@email.com",
                            IdentityNumber = "3850915851",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 41,
                            Name = "Selin",
                            Phone = "(555) 689-0123",
                            PositionID = 11,
                            RegistrationNumber = "118",
                            Surname = "Erdoğan"
                        },
                        new
                        {
                            Id = 20,
                            AppointmentId = 0,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(8982),
                            DepartmentID = 3,
                            Email = "onur.akbas@email.com",
                            IdentityNumber = "3850926751",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 35,
                            Name = "Onur",
                            Phone = "(555) 690-1234",
                            PositionID = 10,
                            RegistrationNumber = "119",
                            Surname = "Akbaş"
                        },
                        new
                        {
                            Id = 21,
                            AppointmentId = 0,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(8984),
                            DepartmentID = 6,
                            Email = "melis.yilmaz@email.com",
                            IdentityNumber = "3880226751",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 34,
                            Name = "Melis",
                            Phone = "(555) 701-2345",
                            PositionID = 9,
                            RegistrationNumber = "120",
                            Surname = "Yılmaz"
                        },
                        new
                        {
                            Id = 22,
                            AppointmentId = 0,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(8987),
                            DepartmentID = 7,
                            Email = "meryem.kuzey@email.com",
                            IdentityNumber = "3972226751",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 35,
                            Name = "Meryem",
                            Phone = "(555) 634-5358",
                            PositionID = 12,
                            RegistrationNumber = "121",
                            Surname = "Kuzey"
                        },
                        new
                        {
                            Id = 23,
                            AppointmentId = 0,
                            CreatedDate = new DateTime(2024, 2, 2, 16, 22, 43, 792, DateTimeKind.Local).AddTicks(8990),
                            DepartmentID = 7,
                            Email = "ali.atabey@email.com",
                            IdentityNumber = "1971927981",
                            IsActive = true,
                            IsDeleted = false,
                            LocationID = 34,
                            Name = "Ali",
                            Phone = "(555) 186-2565",
                            PositionID = 12,
                            RegistrationNumber = "122",
                            Surname = "Atabey"
                        });
                });

            modelBuilder.Entity("PMRU.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocationCenter")
                        .HasColumnType("bit");

                    b.Property<string>("LocationDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 34,
                            IsActive = true,
                            IsDeleted = false,
                            IsLocationCenter = true,
                            LocationDescription = "Genel Müdürlük"
                        },
                        new
                        {
                            Id = 35,
                            IsActive = true,
                            IsDeleted = false,
                            IsLocationCenter = false,
                            LocationDescription = "İzmir"
                        },
                        new
                        {
                            Id = 41,
                            IsActive = true,
                            IsDeleted = false,
                            IsLocationCenter = false,
                            LocationDescription = "İzmit"
                        },
                        new
                        {
                            Id = 72,
                            IsActive = true,
                            IsDeleted = false,
                            IsLocationCenter = false,
                            LocationDescription = "Batman"
                        },
                        new
                        {
                            Id = 71,
                            IsActive = true,
                            IsDeleted = false,
                            IsLocationCenter = false,
                            LocationDescription = "Kırıkkale"
                        });
                });

            modelBuilder.Entity("PMRU.Domain.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PositionDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            IsDeleted = false,
                            PositionDescription = "Güvenlik Şefi"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            IsDeleted = false,
                            PositionDescription = "Güvenlik Görevlisi"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            IsDeleted = false,
                            PositionDescription = "Elektrik Mühendisi"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            IsDeleted = false,
                            PositionDescription = "Makine Mühendisi"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            IsDeleted = false,
                            PositionDescription = "Muhasebe Uzmanı"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            IsDeleted = false,
                            PositionDescription = "Personel Uzmanı"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            IsDeleted = false,
                            PositionDescription = "İnsan Kaynakları Uzmanı"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            IsDeleted = false,
                            PositionDescription = "Yazılım Geliştirici"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            IsDeleted = false,
                            PositionDescription = "Test Uzmanı"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            IsDeleted = false,
                            PositionDescription = "Finans Uzmanı"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            IsDeleted = false,
                            PositionDescription = "Pazarlama Uzmanı"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            IsDeleted = false,
                            PositionDescription = "Doktor"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            IsDeleted = false,
                            PositionDescription = "Hemşire"
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            IsDeleted = false,
                            PositionDescription = "Satış Temsilcisi"
                        });
                });

            modelBuilder.Entity("PMRU.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("01b33042-952a-4636-8d15-682447de311a"),
                            ConcurrencyStamp = "b8189424-ccba-4f5d-87b7-bd74f1a0363d",
                            Name = "SystemAdmin",
                            NormalizedName = "SYSTEMADMIN"
                        },
                        new
                        {
                            Id = new Guid("b56d0892-1daa-4b5d-a6e0-381a250daea1"),
                            ConcurrencyStamp = "b379c5a0-6e68-429a-bcfd-7075c396f1c2",
                            Name = "LocalAdmin",
                            NormalizedName = "LOCALADMIN"
                        },
                        new
                        {
                            Id = new Guid("e3a11d19-3f92-463a-a80d-38228fa18746"),
                            ConcurrencyStamp = "c816d0b3-de61-4cfb-8436-0619fdea4ca9",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        });
                });

            modelBuilder.Entity("PMRU.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("faad6812-0f8e-4342-8738-6dcd5e8ecc09"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d9bde632-1304-4106-b04b-25bb6cd49ef8",
                            Email = "elif.ersoy@email.com",
                            EmailConfirmed = false,
                            FullName = "Elif Ersoy",
                            LockoutEnabled = false,
                            NormalizedEmail = "ELIF.ERSOY@EMAIL.COM",
                            NormalizedUserName = "ELIF.ERSOY@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEK4Ow1ARskueDExECZzaeDf9wZJjoTS38Itol2pRCpGSN9fDHemMC3IuKcD+mHiqGQ==",
                            PhoneNumberConfirmed = false,
                            RegistrationNumber = "107",
                            SecurityStamp = "df898718-7c1e-47dd-9a83-84589b599f72",
                            TwoFactorEnabled = false,
                            UserName = "elif.ersoy@email.com"
                        },
                        new
                        {
                            Id = new Guid("a76eb5c4-eebf-47ec-a274-ca7971bfa4e8"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b72160e9-8cca-4963-afad-f19a8a26abc1",
                            Email = "aylin.gunes@email.com",
                            EmailConfirmed = false,
                            FullName = "Aylin Güneş",
                            LockoutEnabled = false,
                            NormalizedEmail = "AYLIN.GUNES@EMAIL.COM",
                            NormalizedUserName = "AYLIN.GUNES@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOSd8BrUHhLoO47+J58MjAG2dpfmjy0ioTu3yyAjcrwH1SA484eHMxEorHuXy0XY6A==",
                            PhoneNumberConfirmed = false,
                            RegistrationNumber = "110",
                            SecurityStamp = "065ac1dc-452a-4385-8f9d-9d7c37e44d40",
                            TwoFactorEnabled = false,
                            UserName = "aylin.gunes@email.com"
                        },
                        new
                        {
                            Id = new Guid("a3b9e2f7-5c1d-4a88-9f3b-7e6c4d2a1b11"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "20819e51-2a41-4430-8b87-4b7d1b7799e7",
                            Email = "eren.akcay@email.com",
                            EmailConfirmed = false,
                            FullName = "Eren Akçay",
                            LockoutEnabled = false,
                            NormalizedEmail = "EREN.AKCAY@EMAIL.COM",
                            NormalizedUserName = "EREN.AKCAY@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFFek6xznHyrM76KvGxgonkAMWK7AM8kcvSUMiGrtZ7eOF+eBXarZWxqvpIQb5pa4w==",
                            PhoneNumberConfirmed = false,
                            RegistrationNumber = "111",
                            SecurityStamp = "62f17551-0a8f-4aa1-a7c0-729655f2e929",
                            TwoFactorEnabled = false,
                            UserName = "eren.akcay@email.com"
                        },
                        new
                        {
                            Id = new Guid("e2f8d174-4b7a-4c91-b9f2-8dc3a1c45b68"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b354d9f7-2916-4e08-8ead-bbb6b4456eeb",
                            Email = "gulay.kaya@email.com",
                            EmailConfirmed = false,
                            FullName = "Gülay Kaya",
                            LockoutEnabled = false,
                            NormalizedEmail = "GULAY.KAYA@EMAIL.COM",
                            NormalizedUserName = "GULAY.KAYA@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECX0mEuRzlc8tCvRi8ttWvHob0cYUGTT8+q+M3BlilNGL6/NSTOc/aviv3ypnmDxgw==",
                            PhoneNumberConfirmed = false,
                            RegistrationNumber = "112",
                            SecurityStamp = "5105a4b1-5ea1-489a-9b68-0fc51d727007",
                            TwoFactorEnabled = false,
                            UserName = "gulay.kaya@email.com"
                        },
                        new
                        {
                            Id = new Guid("0e7b95a1-9b14-4c87-af3d-1d2f6b8aefc3"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bd9466e4-fe1e-4cb5-9775-468ad7600a1e",
                            Email = "gulsum.aydin@email.com",
                            EmailConfirmed = false,
                            FullName = "Gülsüm Aydın",
                            LockoutEnabled = false,
                            NormalizedEmail = "GULSUM.AYDIN@EMAIL.COM",
                            NormalizedUserName = "GULSUM.AYDIN@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEH2bvc9wkymhwuhi3LjrcvJNQv9cTWMs7ZnnHKsHneGjzTFjET3rAj2ROzyRPJLerQ==",
                            PhoneNumberConfirmed = false,
                            RegistrationNumber = "116",
                            SecurityStamp = "b8d2b46e-3d3d-4f8c-b1b3-f98372e900aa",
                            TwoFactorEnabled = false,
                            UserName = "gulsum.aydin@email.com"
                        },
                        new
                        {
                            Id = new Guid("2b9d163d-cdd1-4b2c-b62e-ec59a6b300fb"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7d8e7efe-53e8-465b-a75f-10902affe58d",
                            Email = "meryem.kuzey@email.com",
                            EmailConfirmed = false,
                            FullName = "Meryem Kuzey",
                            LockoutEnabled = false,
                            NormalizedEmail = "MERYEM.KUZEY@EMAIL.COM",
                            NormalizedUserName = "MERYEM.KUZEY@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDrQGTcEOvrUEAwIi4rYxkFHQ4rHRlOqmCj12aBiZFcsybHHy1j0kDQY/ZWv3udh/w==",
                            PhoneNumberConfirmed = false,
                            RegistrationNumber = "121",
                            SecurityStamp = "8567420e-b85f-4b02-a7e6-146e61561284",
                            TwoFactorEnabled = false,
                            UserName = "meryem.kuzey@email.com"
                        },
                        new
                        {
                            Id = new Guid("b4f91e33-68d1-4aee-b254-d8a53631b23a"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "07d6fc73-49a7-49f8-afbb-1483504ae4da",
                            Email = "ali.atabey@email.com",
                            EmailConfirmed = false,
                            FullName = "Ali Atabey",
                            LockoutEnabled = false,
                            NormalizedEmail = "ALI.ATABEY@EMAIL.COM",
                            NormalizedUserName = "ALI.ATABEY@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOSM4VwLucf3muOpdYouJiETTggJPLbjDiMJBfCMB53YZuhQosCDzZoK2PPPS2+PRQ==",
                            PhoneNumberConfirmed = false,
                            RegistrationNumber = "122",
                            SecurityStamp = "181910b8-003e-40e7-bd3e-0087f68871d9",
                            TwoFactorEnabled = false,
                            UserName = "ali.atabey@email.comm"
                        },
                        new
                        {
                            Id = new Guid("79a21042-ac37-43dc-b246-e1a2c9645afb"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "64a2fc47-1d4a-49e3-b561-7e7fbc3146ce",
                            Email = "cem.yildirim@email.com",
                            EmailConfirmed = false,
                            FullName = "Cem Yıldırım",
                            LockoutEnabled = false,
                            NormalizedEmail = "CEM.YILDIRIM@EMAIL.COM",
                            NormalizedUserName = "CEM.YILDIRIM@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEA0Kl1fizS0jbxPW0AmOY5p1HbiIOHCRVdSyl5PfAjcWX7l5mqyyxJjSsvfyQThvpA==",
                            PhoneNumberConfirmed = false,
                            RegistrationNumber = "113",
                            SecurityStamp = "919c4c88-d165-4de2-81d4-30e6100864d2",
                            TwoFactorEnabled = false,
                            UserName = "cem.yildirim@email.com"
                        },
                        new
                        {
                            Id = new Guid("faad6812-0f8e-4342-aabb-6dcd5e8ecc09"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ee424114-fdbb-4b2b-a074-d529a579070c",
                            Email = "dilara.cetin@email.com",
                            EmailConfirmed = false,
                            FullName = "Dilara Çetin",
                            LockoutEnabled = false,
                            NormalizedEmail = "DILARA.CETIN@EMAIL.COM",
                            NormalizedUserName = "DILARA.CETIN@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEP3EHU2jOUDwW9lPjswd6BDMpymod62xc95lFX8dMH/y4LzfohRtDxLRVp5YaCzug==",
                            PhoneNumberConfirmed = false,
                            RegistrationNumber = "114",
                            SecurityStamp = "608c9233-b751-44b3-87bf-5ab594eb65b2",
                            TwoFactorEnabled = false,
                            UserName = "dilara.cetin@email.com"
                        },
                        new
                        {
                            Id = new Guid("a2b4f813-72c9-4a6e-9d7b-1f8c3d2e5a0f"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8a7e987d-960b-464b-95a9-1c136e343acf",
                            Email = "mert.saglam@email.com",
                            EmailConfirmed = false,
                            FullName = "Mert Sağlam",
                            LockoutEnabled = false,
                            NormalizedEmail = "MERT.SAGLAM@EMAIL.COM",
                            NormalizedUserName = "MERT.SAGLAM@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEB82EVBKuA4OzlyozPsBBb78jYUkpLQeaFi9DKYp54AjTRqTyXOLrxe1uHx/tTEohg==",
                            PhoneNumberConfirmed = false,
                            RegistrationNumber = "115",
                            SecurityStamp = "d3e1c1af-eb34-4180-839e-0488718b8a4f",
                            TwoFactorEnabled = false,
                            UserName = "mert.saglam@email.com"
                        },
                        new
                        {
                            Id = new Guid("3a7f9b68-21d5-4f8c-b2a7-9c0e1f5d2a91"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b4a2314a-32ab-4aed-a693-8f881158867f",
                            Email = "emre.yaman@email.com",
                            EmailConfirmed = false,
                            FullName = "Emre Yaman",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMRE.YAMAN@EMAIL.COM",
                            NormalizedUserName = "EMRE.YAMAN@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPorNHo64/KNkMATdl0ZMoo+VMIUF6utzf+iufHF+UUHI4bmV4avqBbQpgJre0bhhg==",
                            PhoneNumberConfirmed = false,
                            RegistrationNumber = "117",
                            SecurityStamp = "3927a500-7479-4cf9-8eb9-bc29de189e51",
                            TwoFactorEnabled = false,
                            UserName = "emre.yaman@email.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("PMRU.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("PMRU.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("PMRU.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("PMRU.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMRU.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("PMRU.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PMRU.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("PMRU.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMRU.Domain.Entities.Employee", "Employee")
                        .WithOne("Appointment")
                        .HasForeignKey("PMRU.Domain.Entities.Appointment", "EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PMRU.Domain.Entities.Availability", b =>
                {
                    b.HasOne("PMRU.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Availabilities")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("PMRU.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("PMRU.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("PMRU.Domain.Entities.Employee", b =>
                {
                    b.HasOne("PMRU.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PMRU.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PMRU.Domain.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Location");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("PMRU.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Availabilities");
                });

            modelBuilder.Entity("PMRU.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Appointment");
                });
#pragma warning restore 612, 618
        }
    }
}
